= tinyMAS: a Tiny MultiAgent Java Platform

The Tiny Multiagent Platform is a very small platform which permits to implement and run agent-based systems.

This platform was written by Stéphane GALLAND and GAUD Nicolas for the multiagent courses of the Computer Science Department of the link:http://www.utbm.fr[University of Technology of Belfort-Montbéliard].

CAUTION: TinyMAS is no more under development. A large amount of its source code is merged into the link:http://www.janusproject.io[Janus platform].


== tinyMAS: a SARL Run-time Environment

link:http://www.sarl.io[SARL] is a general-purpose agent-oriented language. SARL aims at providing the fundamental abstractions for dealing with concurrency, distribution, interaction, decentralization, reactivity, autonomy and dynamic reconfiguration. These high-level features are now considered as the major requirements for an easy and practical implementation of modern complex software applications.

A SARL Run-time Environment (SRE) executes or interprets compiled SARL code on an "hardware platform." A module of tinyMAS was written to make it a SRE.
The tinyMAS SRE does not support all the elements of the SARL metamodel. Indeed the support for external contexts and inner contexts is not implemented.

A short tutorial in available of the SARL website for creating a SRE with the tinyMAS platform: http://www.sarl.io/docs/suite/io/sarl/docs/tutorials/CreatingASARLRunTimeEnvironmentForTheTinyMASPlatformSpec.html
